# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f1250a609444ad7dbc4f86cc4787e41552de7104acd1fed46230f12a5213c50cd2ab39989b53ddd61ee78c771299a19c31b6d743fa5dfce70b86be0f41a440

test:
  secret_key_base: f114cb4e08a143743861e934bb5ab815a1995f765736f3286dbbbf05739be7c8596c62f4a3bd00ef176b7d82c3d95c8f1109e47223bedf247ee51a819a784325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
